Nav bar
CraftAcademy/slowfood-oct18-team2 pull request #5
Opened 2018-11-28 19:13 UTC by schneiderman805

- creates nav bar at the top of root page

- adds logo to nav bar

- adds a place holder for checkout total

- adds place holders for log in, sign up, and checkout

- adds paths for log in, sign up and checkout links but they have no view yet for this user story

- creates feature file to hold user story and test for nav bar
PT:
https://www.pivotaltracker.com/n/projects/2227584

2018-11-28 19:18 UTC, tochman commented
This is a good example of a PR where a screenshot would come in handy

2018-11-29 14:49 UTC, faraznaeem requested changes
Please delete unnecessary views and refactor them to haml

2018-11-30 07:59 UTC, faraznaeem requested changes

2018-11-30 07:59 UTC, faraznaeem commented on app/views/layouts/application.html.haml
> +    %link{:href => "https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css", :rel => "stylesheet"}/
Hash rockets

2018-11-30 07:59 UTC, faraznaeem commented on config/routes.rb
format code and delete unnecessary lines

2018-11-30 09:26 UTC, faraznaeem approved these changes

2018-11-30 09:27 UTC, merged